INSERT INTO contacts (name, email, company, phone, city, status) VALUES
('Alice Nguyen',   'alice@techcorp.vn',   'TechCorp VN',    '+84 90 111 2233', 'Ho Chi Minh City', 'active'),
('Bob Smith',      'bob@acmeinc.com',     'Acme Inc',       '+1 415 555 0101', 'San Francisco',    'active'),
('Carol Lee',      'carol@startupx.io',   'StartupX',       '+65 9123 4567',   'Singapore',        'lead'),
('David Tran',     'david@vietsoft.vn',   'VietSoft',       '+84 91 222 3344', 'Hanoi',            'active'),
('Eva Muller',     'eva@berlin.tech',     'Berlin Tech GmbH','+49 30 99887766','Berlin',           'inactive'),
('Frank Tan',      'frank@sgfinance.sg',  'SG Finance',     '+65 8765 4321',   'Singapore',        'active'),
('Grace Park',     'grace@seoulsoft.kr',  'SeoulSoft',      '+82 2 555 6677',  'Seoul',            'lead'),
('Henry Wilson',   'henry@globalins.au',  'Global Insurance','+61 2 9876 5432','Sydney',           'active'),
('Iris Chen',      'iris@cloudco.cn',     'CloudCo',        '+86 21 5555 7788','Shanghai',         'active'),
('James Hoang',    'james@hcmdev.vn',     'HCM Dev Studio', '+84 93 444 5566', 'Ho Chi Minh City', 'active'),
('Karen Patel',    'karen@mumbaitech.in', 'Mumbai Tech',    '+91 98765 43210', 'Mumbai',           'lead'),
('Leo Martinez',   'leo@cdmx.mx',         'CDMX Solutions', '+52 55 1234 5678','Mexico City',      'active'),
('Maya Johansson', 'maya@nordic.se',      'Nordic AB',      '+46 8 555 6677',  'Stockholm',        'inactive'),
('Nate Brown',     'nate@nyventures.com', 'NY Ventures',    '+1 212 555 9988', 'New York',         'active'),
('Olivia Santos',  'olivia@sptech.br',    'SP Tech',        '+55 11 9876 5432','São Paulo',        'active');

INSERT INTO deals (contact_id, title, value, stage, owner) VALUES
(1, 'Enterprise licence – TechCorp VN',    85000.00, 'proposal',      'sales_alice'),
(1, 'Support contract renewal',            12000.00, 'closed_won',    'sales_alice'),
(2, 'Platform migration – Acme',          150000.00, 'negotiation',   'sales_bob'),
(3, 'Pilot programme – StartupX',           8500.00, 'prospecting',   'sales_carol'),
(4, 'VietSoft annual subscription',        24000.00, 'qualified',     'sales_alice'),
(5, 'Berlin Tech consulting retainer',     36000.00, 'closed_lost',   'sales_bob'),
(6, 'SG Finance data integration',         62000.00, 'proposal',      'sales_carol'),
(7, 'SeoulSoft POC',                         5000.00, 'prospecting',   'sales_alice'),
(8, 'Global Insurance – workers comp module',200000.00,'negotiation', 'sales_bob'),
(9, 'CloudCo API access',                  18000.00, 'qualified',     'sales_carol'),
(10,'HCM Dev – team licence x10',          16000.00, 'closed_won',    'sales_alice'),
(11,'Mumbai Tech onboarding',               9500.00, 'prospecting',   'sales_bob'),
(12,'CDMX Solutions custom build',         45000.00, 'proposal',      'sales_carol'),
(14,'NY Ventures enterprise deal',        320000.00, 'negotiation',   'sales_bob'),
(15,'SP Tech regional rollout',            78000.00, 'qualified',     'sales_alice');